### ISSUE TITLE
☃

### ISSUE THREAD

**Issue by jboynyc** [simonlindgren/the-materialiser#1]
I think you should switch the spelling The Materializer.

**Comment by simonlindgren** [comment]
Hmm... I was thinking UK spelling... But I guess that some of those -ize/-ise tend to retain the z, also in UK English. Either way, thanks for pointing it out! I'll change it! :-)

**Comment by jboynyc** [comment]
Haha, you actually changed it :) That was a joke!

**Comment by simonlindgren** [comment]
eehh! I feel stupid now! haha
And you put me in a position where changing back will seem equally as odd as keeping 'ize'. Well player, Sir! ;))

If I change it back... Will you then say that it was a joke that is was a joke (ad infinitum)?!

**Comment by simonlindgren** [comment]
eehh! I feel stupid now! haha
And you put me in a position where changing back will seem equally as odd as keeping 'ize'. Well player, Sir! ;))

If I change it back... Will you then say that it was a joke that is was a joke (ad infinitum)?!

Simon

On 26 Oct 2016, at 17:14, John Boy <notifications@github.com<mailto:notifications@github.com>> wrote:


That was a joke!

**Comment by jboynyc** [comment]
did we just invent recursive academic trolling?

**Comment by simonlindgren** [comment]
sure looks like it!
